[package]
name = "rathernet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.3", features = ["derive"] }
cpal = { version = "0.15.2", features = ["asio"] }
hound = "3.5.0"
rodio = "0.17.1"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["full"] }
